#!/usr/bin/env bash

# Purpose:
#
# Installs application dependencies inside app container.

set -e
[ -z "${DEBUG}" ] || set -x

cd "$(dirname "$0")/.."

echo "Updating build dependencies"
./scripts/build yarn install
